services:
  clickhouse: 
    image: clickhouse/clickhouse-server:24.3
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    env_file:
      - .env
    environment:
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
      CLICKHOUSE_DB: ${CLICKHOUSE_DB}
    volumes:
      - clickhouse_data:/var/lib/clickhouse 
      - clickhouse_logs:/var/log/clickhouse-server
    ulimits:
      nofile: 
        soft: 262144
        hard: 262144
    restart: always

  dbmate: 
    image: ghcr.io/amacneil/dbmate:latest
    env_file:
      - .env
    environment:
      - DATABASE_URL=clickhouse://${CLICKHOUSE_USER}:${CLICKHOUSE_PASSWORD}@clickhouse:${CLICKHOUSE_PORT}/${CLICKHOUSE_DB}
    volumes:
      - ./db:/db
    depends_on:
      - clickhouse
    profiles:
      - migrate

networks:
  dds_shared_network: 
    external: True

volumes:
  clickhouse_data:
  clickhouse_logs:



    
